---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false

requirements:
    requiredRam: 1.0
    internetCheckUrl: https://deb.debian.org/
    check:
        - ram
        - power
        - root
    required:
        - ram
        - root
