#!/usr/bin/env bash
# sync-manifest.sh — rebuild the CUMULATIVE signed manifest across ALL published versions and publish it to
# the stable `manifest` GitHub release that updates.shrekos.iambu.dev serves as /stable/SHA256SUMS(.gpg).
#
# systemd-sysupdate wants ONE SHA256SUMS listing every offered version at the base URL. Per-version releases
# (v1, v2, ...) each carry only their own lines, so this aggregates them, re-signs the union with the
# update-signing key, and force-updates a single stable `manifest` release. Run AFTER publish-release.sh
# cuts a new v<N> (for v1, cumulative == per-release, but run it anyway so the stable tag exists).
#
#   scripts/sync-manifest.sh [--repo OWNER/REPO] [--signing-key DIR]
set -euo pipefail
REPO_ROOT="$(git rev-parse --show-toplevel)"; cd "$REPO_ROOT"

REPO=constant-itis/shrek-os
GH_PUSH_USER=constant-itis
GH_RESTORE_USER=BuberryWorldwide
MANIFEST_TAG=manifest
SIGNING_KEY="${UPDATE_GNUPGHOME:-$HOME/vault/shrek-os/update-signing/gnupg}"

while [ $# -gt 0 ]; do
  case "$1" in
    --repo) shift; REPO="$1" ;;
    --signing-key) shift; SIGNING_KEY="$1" ;;
    -h|--help) sed -n '2,11p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
  shift
done

[ -d "$SIGNING_KEY" ] || { echo "ABORT: update-signing key not at $SIGNING_KEY (see docs/update-key-rotation.md)" >&2; exit 1; }

WORK="$(mktemp -d)"
gh auth switch --user "$GH_PUSH_USER" >/dev/null 2>&1 || { echo "cannot switch gh to $GH_PUSH_USER" >&2; exit 1; }
trap 'rm -rf "$WORK"; gh auth switch --user "$GH_RESTORE_USER" >/dev/null 2>&1 || true' EXIT

# Collect every versioned release's SHA256SUMS.
tags=$(gh release list --repo "$REPO" --limit 200 --json tagName -q '.[].tagName' | grep -E '^v[0-9]+$' || true)
[ -n "$tags" ] || { echo "no v<N> releases found on $REPO" >&2; exit 1; }
: > "$WORK/cumulative"
echo "aggregating manifests:" >&2
for t in $tags; do
  if gh release download "$t" --repo "$REPO" --pattern SHA256SUMS --dir "$WORK/$t" >/dev/null 2>&1; then
    cat "$WORK/$t/SHA256SUMS" >> "$WORK/cumulative"
    echo "  + $t" >&2
  else
    echo "  ! $t has no SHA256SUMS — skipped" >&2
  fi
done

# Union, stable-sorted. A filename appearing twice with DIFFERENT hashes is a corruption — fail closed.
sort -u "$WORK/cumulative" | awk 'NF' > "$WORK/SHA256SUMS"
dups=$(awk '{print $2}' "$WORK/SHA256SUMS" | sort | uniq -d)
[ -z "$dups" ] || { echo "ABORT: same filename, different hashes across releases: $dups" >&2; exit 1; }
echo "cumulative SHA256SUMS ($(wc -l < "$WORK/SHA256SUMS") entries):"; sed 's/^/  /' "$WORK/SHA256SUMS"

# Sign + self-verify (fail closed).
GNUPGHOME="$SIGNING_KEY" gpg --batch --yes --detach-sign -o "$WORK/SHA256SUMS.gpg" "$WORK/SHA256SUMS"
GNUPGHOME="$SIGNING_KEY" gpg --verify "$WORK/SHA256SUMS.gpg" "$WORK/SHA256SUMS" 2>/dev/null \
  || { echo "cumulative manifest failed self-verify against $SIGNING_KEY — aborting" >&2; exit 1; }

NOTES="Stable cumulative update manifest served by updates.shrekos.iambu.dev as /stable/SHA256SUMS(.gpg). Regenerated by scripts/sync-manifest.sh across all v<N> releases. NOT a versioned image release — carries only the signed manifest."
if gh release view "$MANIFEST_TAG" --repo "$REPO" >/dev/null 2>&1; then
  gh release upload "$MANIFEST_TAG" --repo "$REPO" --clobber "$WORK/SHA256SUMS" "$WORK/SHA256SUMS.gpg"
else
  gh release create "$MANIFEST_TAG" --repo "$REPO" --title "Update manifest (cumulative)" --notes "$NOTES" \
    "$WORK/SHA256SUMS" "$WORK/SHA256SUMS.gpg"
fi
echo "published cumulative manifest -> release '$MANIFEST_TAG' on $REPO"
