# Shrek OS INSTALL-0 Calamares configuration.
---
modules-search: [ local, /usr/lib/calamares/modules ]
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - shrekdeploy
- show:
  - finished

branding: shrek
prompt-install: true
dont-chroot: false
